feat: add polygon logs processing - Closes #issue-8
IlluvatarEru/mev-inspect-py pull request #11
Opened 2022-12-15 18:59 UTC by IlluvatarEru

Signed-off-by: Arthurim <arthurbdauphine@gmail.com>

## What does this PR do?

This PR adds logs processing for Polygon.

## Related issue

Closes #8 

## Testing
Using a Pocket Network RPC URL for Polygon, I ran several instances of `inspect-many` (eg: ./mev inspect-many 34500000 34500100`) and it correctly detected mev transactions.

## Checklist before merging
- [x] Read the [contributing guide](https://github.com/flashbots/mev-inspect-py/blob/main/CONTRIBUTING.md)
- [x] Installed and ran pre-commit hooks
- [x] All tests pass with `./mev test`

2022-12-20 02:43 UTC, 0xpanoramix commented on mev_inspect/inspect_block.py
> +        # @TODO: Write profits to DB
Nice, I'm just marking this for reference

2022-12-20 02:45 UTC, 0xpanoramix requested changes

2022-12-20 08:22 UTC, IlluvatarEru commented on mev_inspect/queue/tasks.py
> -        with _session_scope(DbMiddleware.get_trace_sessionmaker()) as trace_db_session:
`trace_db_session` and `inspect_db_session` are not used anymore in `inspect_many_blocks`

2022-12-21 04:58 UTC, 0xpanoramix commented on mev_inspect/queue/tasks.py
> -        with _session_scope(DbMiddleware.get_trace_sessionmaker()) as trace_db_session:
I think we will need to keep the inspect_db_session as we will use it to store data in the Inspect DB, but feel free to remove the trace db session and then merge !

2022-12-21 12:02 UTC, IlluvatarEru commented on mev_inspect/queue/tasks.py
> -        with _session_scope(DbMiddleware.get_trace_sessionmaker()) as trace_db_session:
Alright, added `inspect_db_session` back

2022-12-21 21:17 UTC, 0xpanoramix approved these changes

2022-12-22 10:31 UTC, merged